"""Add multi-device support with DeviceUserMapping and device_id in attendance_logs

Revision ID: 8f63119d258c
Revises: 
Create Date: 2025-10-02 11:00:37.449171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f63119d258c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_user_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('device_user_id', sa.String(length=50), nullable=False),
    sa.Column('system_user_id', sa.Integer(), nullable=False),
    sa.Column('is_conflict_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device_settings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'device_user_id', name='unique_device_user_mapping')
    )
    with op.batch_alter_table('device_user_mappings', schema=None) as batch_op:
        batch_op.create_index('idx_device_user_mapping', ['device_id', 'device_user_id'], unique=False)

    op.drop_table('_alembic_tmp_daily_attendance')
    op.drop_table('notifications')
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_attendance_device', ['device_id'], unique=False)
        batch_op.create_index('idx_attendance_device_ip', ['device_ip'], unique=False)
        batch_op.create_foreign_key('fk_attendance_logs_device_id', 'device_settings', ['device_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('daily_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_daily_attendance_leave_request'))
        batch_op.drop_index(batch_op.f('idx_daily_attendance_leave_type'))
        batch_op.drop_index(batch_op.f('idx_daily_attendance_paid_holiday'))
        batch_op.create_foreign_key('fk_daily_attendance_leave_type', 'leave_types', ['leave_type_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_daily_attendance_paid_holiday', 'paid_holidays', ['paid_holiday_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_daily_attendance_leave_request', 'leave_requests', ['leave_request_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('employee_attachments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.alter_column('leave_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_leave_requests_leave_type'))
        batch_op.create_index('idx_leave_dates', ['start_date', 'end_date'], unique=False)
        batch_op.create_foreign_key('fk_leave_requests_leave_type', 'leave_types', ['leave_type_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('general_manager_status')
        batch_op.drop_column('general_manager_updated_at')
        batch_op.drop_column('general_manager_comment')

    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_leave_types_name', ['name'])

    with op.batch_alter_table('paid_holidays', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_paid_holidays_holiday_type'))
        batch_op.drop_index(batch_op.f('idx_paid_holidays_start_date'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_paid_holidays_created_by', 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('permission_requests', schema=None) as batch_op:
        batch_op.drop_column('manager_status')
        batch_op.drop_column('director_comment')
        batch_op.drop_column('manager_comment')
        batch_op.drop_column('manager_updated_at')
        batch_op.drop_column('director_status')
        batch_op.drop_column('director_updated_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('salary',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('salary',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('permission_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director_updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('director_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('manager_updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('manager_comment', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('director_comment', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manager_status', sa.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('paid_holidays', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_index(batch_op.f('idx_paid_holidays_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_paid_holidays_holiday_type'), ['holiday_type'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('general_manager_comment', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('general_manager_updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('general_manager_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_leave_dates')
        batch_op.create_index(batch_op.f('idx_leave_requests_leave_type'), ['leave_type_id'], unique=False)
        batch_op.alter_column('leave_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('employee_attachments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('daily_attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_daily_attendance_paid_holiday'), ['paid_holiday_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_daily_attendance_leave_type'), ['leave_type_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_daily_attendance_leave_request'), ['leave_request_id'], unique=False)

    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_attendance_device_ip')
        batch_op.drop_index('idx_attendance_device')
        batch_op.drop_column('device_id')

    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('notification_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('reference_id', sa.INTEGER(), nullable=True),
    sa.Column('reference_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_alembic_tmp_daily_attendance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('first_check_in', sa.DATETIME(), nullable=True),
    sa.Column('last_check_out', sa.DATETIME(), nullable=True),
    sa.Column('total_working_hours', sa.FLOAT(), nullable=True),
    sa.Column('total_breaks', sa.INTEGER(), nullable=True),
    sa.Column('entry_count', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('status_reason', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_day_off', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_late', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('leave_request_id', sa.INTEGER(), nullable=True),
    sa.Column('leave_type_id', sa.INTEGER(), nullable=True),
    sa.Column('paid_holiday_id', sa.INTEGER(), nullable=True),
    sa.Column('is_paid_holiday', sa.BOOLEAN(), nullable=True),
    sa.Column('leave_type_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('holiday_name', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['leave_request_id'], ['leave_requests.id'], name=op.f('fk_daily_attendance_leave_request'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], name=op.f('fk_daily_attendance_leave_type'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paid_holiday_id'], ['paid_holidays.id'], name=op.f('fk_daily_attendance_paid_holiday'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_user_mappings', schema=None) as batch_op:
        batch_op.drop_index('idx_device_user_mapping')

    op.drop_table('device_user_mappings')
    # ### end Alembic commands ###
