"""Fix attendance_logs timestamp column type from text to timestamp

Revision ID: a8c2dbd0a24d
Revises: cca6c6640ad0
Create Date: 2025-11-04 14:19:10.970893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c2dbd0a24d'
down_revision = 'cca6c6640ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint_number', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint_number')
    )
    with op.batch_alter_table('deleted_users', schema=None) as batch_op:
        batch_op.create_index('idx_deleted_user_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('idx_deleted_user_fingerprint', ['fingerprint_number'], unique=False)

    op.create_table('employee_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sqlite_sequence')
    # Fix timestamp column BEFORE batch_alter_table (PostgreSQL requires direct ALTER)
    op.execute("""
        ALTER TABLE attendance_logs 
        ALTER COLUMN timestamp TYPE timestamp without time zone 
        USING timestamp::timestamp without time zone
    """)
    op.execute("ALTER TABLE attendance_logs ALTER COLUMN timestamp SET NOT NULL")
    
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('device_id',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('device_ip',
               existing_type=sa.TEXT(),
               type_=sa.String(length=15),
               nullable=False)
        batch_op.alter_column('scan_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=False)
        batch_op.alter_column('duration',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('pair_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('scan_order',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('raw_scan_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('check_in_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('check_out_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_index('idx_attendance_device', ['device_id'], unique=False)
        batch_op.create_index('idx_attendance_device_ip', ['device_ip'], unique=False)
        batch_op.create_index('idx_attendance_scan_type', ['scan_type'], unique=False)
        batch_op.create_index('idx_attendance_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('idx_attendance_user_date', ['user_id', sa.literal_column('DATE(timestamp)')], unique=False)
        batch_op.create_index('idx_attendance_user_timestamp', ['user_id', 'timestamp'], unique=False)
        batch_op.create_foreign_key(None, 'attendance_logs', ['check_out_id'], ['id'])
        batch_op.create_foreign_key(None, 'device_settings', ['device_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'attendance_logs', ['check_in_id'], ['id'])

    with op.batch_alter_table('daily_attendance', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'leave_requests', ['leave_request_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'leave_types', ['leave_type_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'paid_holidays', ['paid_holiday_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('department_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('manager_id',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['manager_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('device_settings', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('device_ip',
               existing_type=sa.TEXT(),
               type_=sa.String(length=15),
               nullable=False)
        batch_op.alter_column('device_port',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('device_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BIGINT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('device_users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('device_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('device_user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('device_uid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('device_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('privilege',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('group_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('card',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('is_processed',
               existing_type=sa.BIGINT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('system_user_id',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_index('idx_device_user_device_id', ['device_id'], unique=False)
        batch_op.create_index('idx_device_user_device_user_id', ['device_user_id'], unique=False)
        batch_op.create_index('idx_device_user_processed', ['is_processed'], unique=False)
        batch_op.create_index('idx_device_user_system_user', ['system_user_id'], unique=False)
        batch_op.create_foreign_key(None, 'device_settings', ['device_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['system_user_id'], ['id'], ondelete='SET NULL')

    # Fix fingerprint_failures timestamp column BEFORE batch_alter_table
    op.execute("""
        ALTER TABLE fingerprint_failures 
        ALTER COLUMN timestamp TYPE timestamp without time zone 
        USING timestamp::timestamp without time zone
    """)
    op.execute("ALTER TABLE fingerprint_failures ALTER COLUMN timestamp SET NOT NULL")
    
    with op.batch_alter_table('fingerprint_failures', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('device_ip',
               existing_type=sa.TEXT(),
               type_=sa.String(length=15),
               nullable=False)
        batch_op.alter_column('error_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('employee_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('resolved',
               existing_type=sa.BIGINT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('manual_entry',
               existing_type=sa.BIGINT(),
               type_=sa.Boolean(),
               existing_nullable=True)

    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('leave_type_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('total_days',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('used_days',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('remaining_days',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('manual_remaining_days',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('year',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'leave_types', ['leave_type_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('leave_type_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('delegate_employee_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('manager_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('manager_updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('admin_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('admin_updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_index('idx_leave_admin_status', ['admin_status'], unique=False)
        batch_op.create_index('idx_leave_dates', ['start_date', 'end_date'], unique=False)
        batch_op.create_index('idx_leave_manager_status', ['manager_status'], unique=False)
        batch_op.create_index('idx_leave_status', ['status'], unique=False)
        batch_op.create_index('idx_leave_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'leave_types', ['leave_type_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['delegate_employee_id'], ['id'])

    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('color',
               existing_type=sa.TEXT(),
               type_=sa.String(length=7),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BIGINT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('requires_balance',
               existing_type=sa.BIGINT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('paid_holidays', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('holiday_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('is_recurring',
               existing_type=sa.BIGINT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('permission_requests', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('admin_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('admin_updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('smtp_configurations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('smtp_server',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('smtp_port',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('smtp_username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('smtp_password',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('use_tls',
               existing_type=sa.BIGINT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('use_ssl',
               existing_type=sa.BIGINT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('sender_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('sender_email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BIGINT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('notify_leave_requests',
               existing_type=sa.BIGINT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('notify_permission_requests',
               existing_type=sa.BIGINT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('notify_admin_only',
               existing_type=sa.BIGINT(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               nullable=False)
        batch_op.alter_column('fingerprint_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('avaya_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('department_id',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('profile_picture',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('joining_date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('alternate_phone_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_index('idx_user_department', ['department_id'], unique=False)
        batch_op.create_index('idx_user_fingerprint', ['fingerprint_number'], unique=False)
        batch_op.create_index('idx_user_role', ['role'], unique=False)
        batch_op.create_index('idx_user_status', ['status'], unique=False)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['fingerprint_number'])
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_user_status')
        batch_op.drop_index('idx_user_role')
        batch_op.drop_index('idx_user_fingerprint')
        batch_op.drop_index('idx_user_department')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('alternate_phone_number',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('joining_date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('profile_picture',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('department_id',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('avaya_number',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fingerprint_number',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('smtp_configurations', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('notify_admin_only',
               existing_type=sa.Boolean(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('notify_permission_requests',
               existing_type=sa.Boolean(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('notify_leave_requests',
               existing_type=sa.Boolean(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.Boolean(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('sender_email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('sender_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('use_ssl',
               existing_type=sa.Boolean(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('use_tls',
               existing_type=sa.Boolean(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('smtp_password',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('smtp_username',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('smtp_port',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('smtp_server',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('permission_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('admin_updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('admin_status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('paid_holidays', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('is_recurring',
               existing_type=sa.Boolean(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('holiday_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('requires_balance',
               existing_type=sa.Boolean(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.Boolean(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('color',
               existing_type=sa.String(length=7),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_leave_user_created')
        batch_op.drop_index('idx_leave_status')
        batch_op.drop_index('idx_leave_manager_status')
        batch_op.drop_index('idx_leave_dates')
        batch_op.drop_index('idx_leave_admin_status')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('admin_updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('admin_status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('manager_updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('manager_status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('delegate_employee_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('leave_type_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('year',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('manual_remaining_days',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('remaining_days',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('used_days',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('total_days',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('leave_type_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('fingerprint_failures', schema=None) as batch_op:
        batch_op.alter_column('manual_entry',
               existing_type=sa.Boolean(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('resolved',
               existing_type=sa.Boolean(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('employee_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('error_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('device_ip',
               existing_type=sa.String(length=15),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('device_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_device_user_system_user')
        batch_op.drop_index('idx_device_user_processed')
        batch_op.drop_index('idx_device_user_device_user_id')
        batch_op.drop_index('idx_device_user_device_id')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('system_user_id',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('is_processed',
               existing_type=sa.Boolean(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('card',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('group_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('privilege',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('device_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('device_uid',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('device_user_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('device_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('device_settings', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.Boolean(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('device_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('device_port',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('device_ip',
               existing_type=sa.String(length=15),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('manager_id',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('department_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('daily_attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_attendance_user_timestamp')
        batch_op.drop_index('idx_attendance_user_date')
        batch_op.drop_index('idx_attendance_timestamp')
        batch_op.drop_index('idx_attendance_scan_type')
        batch_op.drop_index('idx_attendance_device_ip')
        batch_op.drop_index('idx_attendance_device')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('check_out_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('check_in_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('raw_scan_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('scan_order',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('pair_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('scan_type',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('device_ip',
               existing_type=sa.String(length=15),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('device_id',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seq', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_table('employee_attachments')
    with op.batch_alter_table('deleted_users', schema=None) as batch_op:
        batch_op.drop_index('idx_deleted_user_fingerprint')
        batch_op.drop_index('idx_deleted_user_deleted_at')

    op.drop_table('deleted_users')
    # ### end Alembic commands ###
