"""Add activity_log table

Revision ID: add_activity_log
Revises: 567f33b663bd
Create Date: 2025-11-23 10:47:50.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_activity_log'
down_revision = '567f33b663bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('before_values', sa.Text(), nullable=True),
    sa.Column('after_values', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index('idx_activity_log_user', ['user_id'], unique=False)
        batch_op.create_index('idx_activity_log_created', ['created_at'], unique=False)
        batch_op.create_index('idx_activity_log_action', ['action'], unique=False)
        batch_op.create_index('idx_activity_log_entity', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_activity_log_entity')
        batch_op.drop_index('idx_activity_log_action')
        batch_op.drop_index('idx_activity_log_created')
        batch_op.drop_index('idx_activity_log_user')

    op.drop_table('activity_logs')
    # ### end Alembic commands ###

