"""Add delegate_employee_id to LeaveRequest model

Revision ID: cca6c6640ad0
Revises: a240031710fa
Create Date: 2025-10-26 16:05:11.491266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca6c6640ad0'
down_revision = 'a240031710fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.create_index('idx_attendance_device', ['device_id'], unique=False)
        batch_op.create_index('idx_attendance_device_ip', ['device_ip'], unique=False)
        batch_op.create_foreign_key('fk_attendance_logs_device_id', 'device_settings', ['device_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('daily_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_daily_attendance_leave_request'))
        batch_op.drop_index(batch_op.f('idx_daily_attendance_leave_type'))
        batch_op.drop_index(batch_op.f('idx_daily_attendance_paid_holiday'))
        batch_op.create_foreign_key('fk_daily_attendance_leave_request_id', 'leave_requests', ['leave_request_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_daily_attendance_leave_type_id', 'leave_types', ['leave_type_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_daily_attendance_paid_holiday_id', 'paid_holidays', ['paid_holiday_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('employee_attachments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delegate_employee_id', sa.Integer(), nullable=True))
        batch_op.alter_column('leave_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_leave_requests_leave_type'))
        batch_op.create_index('idx_leave_dates', ['start_date', 'end_date'], unique=False)
        batch_op.create_foreign_key('fk_leave_requests_leave_type_id', 'leave_types', ['leave_type_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_leave_requests_delegate_employee_id', 'users', ['delegate_employee_id'], ['id'])
        batch_op.drop_column('general_manager_status')
        batch_op.drop_column('general_manager_updated_at')
        batch_op.drop_column('is_auto_approved')
        batch_op.drop_column('created_by')
        batch_op.drop_column('general_manager_comment')

    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_leave_types_name', ['name'])

    with op.batch_alter_table('paid_holidays', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_paid_holidays_holiday_type'))
        batch_op.drop_index(batch_op.f('idx_paid_holidays_start_date'))
        batch_op.create_foreign_key('fk_paid_holidays_created_by', 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('permission_requests', schema=None) as batch_op:
        batch_op.drop_column('manager_updated_at')
        batch_op.drop_column('director_status')
        batch_op.drop_column('manager_status')
        batch_op.drop_column('director_comment')
        batch_op.drop_column('director_updated_at')
        batch_op.drop_column('manager_comment')
        batch_op.drop_column('is_auto_approved')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('salary',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('salary',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('permission_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('is_auto_approved', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('manager_comment', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('director_updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('director_comment', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manager_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('director_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('manager_updated_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('paid_holidays', schema=None) as batch_op:
        batch_op.drop_constraint('fk_paid_holidays_created_by', type_='foreignkey')
        batch_op.create_foreign_key('fk_paid_holidays_created_by', 'users', ['created_by'], ['id'])
        batch_op.create_index(batch_op.f('idx_paid_holidays_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_paid_holidays_holiday_type'), ['holiday_type'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.drop_constraint('uq_leave_types_name', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('general_manager_comment', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('is_auto_approved', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('general_manager_updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('general_manager_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint('fk_leave_requests_leave_type_id', type_='foreignkey')
        batch_op.drop_constraint('fk_leave_requests_delegate_employee_id', type_='foreignkey')
        batch_op.drop_index('idx_leave_dates')
        batch_op.create_index(batch_op.f('idx_leave_requests_leave_type'), ['leave_type_id'], unique=False)
        batch_op.alter_column('leave_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('delegate_employee_id')

    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('employee_attachments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('daily_attendance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_daily_attendance_leave_request_id', type_='foreignkey')
        batch_op.drop_constraint('fk_daily_attendance_leave_type_id', type_='foreignkey')
        batch_op.drop_constraint('fk_daily_attendance_paid_holiday_id', type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_daily_attendance_paid_holiday'), ['paid_holiday_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_daily_attendance_leave_type'), ['leave_type_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_daily_attendance_leave_request'), ['leave_request_id'], unique=False)

    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attendance_logs_device_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_attendance_logs_device_id', 'device_settings', ['device_id'], ['id'])
        batch_op.drop_index('idx_attendance_device_ip')
        batch_op.drop_index('idx_attendance_device')

    op.create_table('allowed_domains',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    # ### end Alembic commands ###
