"""Add DeviceUser model for storing users found on devices

Revision ID: eb2d1bc24a06
Revises: 4017d8cdcea0
Create Date: 2025-10-02 15:57:24.235425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2d1bc24a06'
down_revision = '4017d8cdcea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('device_user_id', sa.String(length=50), nullable=False),
    sa.Column('device_uid', sa.String(length=50), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('privilege', sa.String(length=20), nullable=True),
    sa.Column('group_id', sa.String(length=50), nullable=True),
    sa.Column('card', sa.String(length=50), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('system_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device_settings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_users', schema=None) as batch_op:
        batch_op.create_index('idx_device_user_device_id', ['device_id'], unique=False)
        batch_op.create_index('idx_device_user_device_user_id', ['device_user_id'], unique=False)
        batch_op.create_index('idx_device_user_processed', ['is_processed'], unique=False)
        batch_op.create_index('idx_device_user_system_user', ['system_user_id'], unique=False)

    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.create_index('idx_attendance_device', ['device_id'], unique=False)
        batch_op.create_index('idx_attendance_device_ip', ['device_ip'], unique=False)
        batch_op.drop_constraint('fk_attendance_logs_device_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_attendance_logs_device_id', 'device_settings', ['device_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('daily_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_daily_attendance_leave_request'))
        batch_op.drop_index(batch_op.f('idx_daily_attendance_leave_type'))
        batch_op.drop_index(batch_op.f('idx_daily_attendance_paid_holiday'))
        batch_op.create_foreign_key('fk_daily_attendance_paid_holiday_id', 'paid_holidays', ['paid_holiday_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_daily_attendance_leave_request_id', 'leave_requests', ['leave_request_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_daily_attendance_leave_type_id', 'leave_types', ['leave_type_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('employee_attachments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.alter_column('leave_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_leave_requests_leave_type'))
        batch_op.create_index('idx_leave_dates', ['start_date', 'end_date'], unique=False)
        batch_op.create_foreign_key('fk_leave_requests_leave_type_id', 'leave_types', ['leave_type_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('general_manager_status')
        batch_op.drop_column('general_manager_comment')
        batch_op.drop_column('general_manager_updated_at')

    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_leave_types_name', ['name'])

    with op.batch_alter_table('paid_holidays', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_paid_holidays_holiday_type'))
        batch_op.drop_index(batch_op.f('idx_paid_holidays_start_date'))
        batch_op.drop_constraint('fk_paid_holidays_created_by', type_='foreignkey')
        batch_op.create_foreign_key('fk_paid_holidays_created_by', 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('permission_requests', schema=None) as batch_op:
        batch_op.drop_column('director_comment')
        batch_op.drop_column('director_updated_at')
        batch_op.drop_column('director_status')
        batch_op.drop_column('manager_updated_at')
        batch_op.drop_column('manager_status')
        batch_op.drop_column('manager_comment')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('salary',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('salary',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('permission_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_comment', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('manager_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('manager_updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('director_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('director_updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('director_comment', sa.TEXT(), nullable=True))

    with op.batch_alter_table('paid_holidays', schema=None) as batch_op:
        batch_op.drop_constraint('fk_paid_holidays_created_by', type_='foreignkey')
        batch_op.create_foreign_key('fk_paid_holidays_created_by', 'users', ['created_by'], ['id'])
        batch_op.create_index(batch_op.f('idx_paid_holidays_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_paid_holidays_holiday_type'), ['holiday_type'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.drop_constraint('uq_leave_types_name', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('general_manager_updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('general_manager_comment', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('general_manager_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint('fk_leave_requests_leave_type_id', type_='foreignkey')
        batch_op.drop_index('idx_leave_dates')
        batch_op.create_index(batch_op.f('idx_leave_requests_leave_type'), ['leave_type_id'], unique=False)
        batch_op.alter_column('leave_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('employee_attachments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('daily_attendance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_daily_attendance_leave_type_id', type_='foreignkey')
        batch_op.drop_constraint('fk_daily_attendance_leave_request_id', type_='foreignkey')
        batch_op.drop_constraint('fk_daily_attendance_paid_holiday_id', type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_daily_attendance_paid_holiday'), ['paid_holiday_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_daily_attendance_leave_type'), ['leave_type_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_daily_attendance_leave_request'), ['leave_request_id'], unique=False)

    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attendance_logs_device_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_attendance_logs_device_id', 'device_settings', ['device_id'], ['id'])
        batch_op.drop_index('idx_attendance_device_ip')
        batch_op.drop_index('idx_attendance_device')

    with op.batch_alter_table('device_users', schema=None) as batch_op:
        batch_op.drop_index('idx_device_user_system_user')
        batch_op.drop_index('idx_device_user_processed')
        batch_op.drop_index('idx_device_user_device_user_id')
        batch_op.drop_index('idx_device_user_device_id')

    op.drop_table('device_users')
    # ### end Alembic commands ###
